apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bartzwemmer/iac.git
    targetRevision: HEAD
    path: airflow-k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true    
